name: Build, Test, and Push Java Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK and Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        # cache: 'maven'

    - name: Build with Maven
      run: mvn clean package
      working-directory: java-docker-app

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build Docker image
    - name: Build Docker Image
      run: |
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/java-docker-app:latest"
        docker build -t java-docker-app:latest .
        docker tag java-docker-app:latest $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    # Step 5: Push Docker image to Amazon ECR
    - name: Push to Amazon ECR
      run: docker push $IMAGE_URI